[korisnici]
trener_marko = { password = "marko123", uloga = "trener", full_name = "Marko Jovanović", clients_ids = ["petar", "stefan"] }
trener_nikola = { password = "nikola123", uloga = "trener", full_name = "Nikola Arsić", clients_ids = ["milan", "ana", "djordje"] }
trener_zeljko = { password = "zeljko123", uloga = "trener", full_name = "Željko Petrović", clients_ids = ["marija", "luka"] }

petar = { password = "petar123", uloga = "klijent", coach_id = "trener_marko", full_name = "Petar Nikolić", client_id = "petar" }
stefan = { password = "stefan123", uloga = "klijent", coach_id = "trener_marko", full_name = "Stefan Đorđević", client_id = "stefan" }

milan = { password = "milan123", uloga = "klijent", coach_id = "trener_nikola", full_name = "Milan Stojanović", client_id = "milan" }
ana = { password = "ana123", uloga = "klijent", coach_id = "trener_nikola", full_name = "Ana Milošević", client_id = "ana" }
djordje = { password = "djordje123", uloga = "klijent", coach_id = "trener_nikola", full_name = "Đorđe Vasić", client_id = "djordje" }

marija = { password = "marija123", uloga = "klijent", coach_id = "trener_zeljko", full_name = "Marija Jovanović", client_id = "marija" }
luka = { password = "luka123", uloga = "klijent", coach_id = "trener_zeljko", full_name = "Luka Đorđević", client_id = "luka" }