[korisnici]
trener_marko = { lozinka = "marko123", uloga = "trener", ime = "Marko Jovanović", clients_ids = ["petar", "stefan"] }
trener_nikola = { lozinka = "nikola123", uloga = "trener", ime = "Nikola Arsić", clients_ids = ["milan", "ana", "djordje"] }
trener_zeljko = { lozinka = "zeljko123", uloga = "trener", ime = "Željko Petrović", clients_ids = ["marija", "luka"] }

petar = { lozinka = "petar123", uloga = "klijent", coach_id = "trener_marko", ime = "Petar Nikolić", client_id = "petar" }
stefan = { lozinka = "stefan123", uloga = "klijent", coach_id = "trener_marko", ime = "Stefan Đorđević", client_id = "stefan" }

milan = { lozinka = "milan123", uloga = "klijent", coach_id = "trener_nikola", ime = "Milan Stojanović", client_id = "milan" }
ana = { lozinka = "ana123", uloga = "klijent", coach_id = "trener_nikola", ime = "Ana Milošević", client_id = "ana" }
djordje = { lozinka = "djordje123", uloga = "klijent", coach_id = "trener_nikola", ime = "Đorđe Vasić", client_id = "djordje" }

marija = { lozinka = "marija123", uloga = "klijent", coach_id = "trener_zeljko", ime = "Marija Jovanović", client_id = "marija" }
luka = { lozinka = "luka123", uloga = "klijent", coach_id = "trener_zeljko", ime = "Luka Đorđević", client_id = "luka" }